### ISSUE TITLE
problem: initial identity tree data is rendered twice

### ISSUE THREAD

**Issue by gazhayes** [nostrocket/oxygen#12]
Introduced in https://github.com/nostrocket/oxygen/commit/84a65c6d9d35325f98c459d60b588cc700dfe76c

<img width="1070" alt="Screenshot 2023-10-19 at 1 09 55 PM" src="https://github.com/nostrocket/oxygen/assets/8143945/f25511eb-72af-4ce1-ba63-46ea7c167530">

**Comment by shaibearary** [comment]
the easiest way is comment this line
https://github.com/nostrocket/oxygen/blob/91a743651e5508c79a0ae4424c846984b9330907/src/components/views/Identity.svelte#L74
but i think @samuelralak is half way of refector some code of identity component right?

**Comment by samuelralak** [comment]
@shaibearary yes, you are correct. But submitting a PR shortly to comment that out until refactor is complete
