### ISSUE TITLE
problem: mempool view shows event creation time in seconds

### ISSUE THREAD

**Issue by gazhayes** [nostrocket/oxygen#22]
problem: mempool view shows event creation time in seconds

this is a problem because it's ugly.

We used to use moment.js for this kind of thing but I think there are better options now

**Comment by samuelralak** [comment]
in progress

**Comment by samuelralak** [comment]
@gazhayes using `https://github.com/date-fns/date-fns` - a smaller and more performant alternative to momentjs.
