### ISSUE TITLE
problem: not all problems are being rendered 

### ISSUE THREAD

**Issue by gazhayes** [nostrocket/oxygen#33]
All problems exist in currentTipState, and the issue is not with the filter (this can be verified by setting `bypass` to `true`).

The problem must be further downstream, probably in ProblemList.svelte

Introduced in https://github.com/nostrocket/oxygen/pull/28/commits/023ca3b5ee624795baca84b6b798a1397d279c57

**Comment by gazhayes** [comment]
related: https://github.com/nostrocket/oxygen/issues/32

**Comment by samuelralak** [comment]
in progress
