### ISSUE TITLE
problem: child problems that match a filter are not rendered

### ISSUE THREAD

**Issue by gazhayes** [nostrocket/oxygen#37]
problem: child problems that match a filter are not rendered

e.g. `24 oct test` (`321e1ead277a2782f00460d7a0d811de4a866fd16ddc8f4d1df79e9eda78c7c2`) is not rendered when filtering for 24

**Comment by samuelralak** [comment]
@gazhayes noticed this. related #24 I believe

**Comment by gazhayes** [comment]
Yeah I realised it's a duplicate after I logged it, but since you've refactored the problem tracker I closed the original.

**Comment by samuelralak** [comment]
Fixed by #42
