### ISSUE TITLE
Problem: Can't log problem at root level

### ISSUE THREAD

**Issue by samuelralak** [nostrocket/oxygen#48]
Problem:
Getting attached error when trying to log a problem at root level

<img width="645" alt="Screenshot 2023-10-28 at 18 31 23" src="https://github.com/nostrocket/oxygen/assets/4476552/caf253e0-96dd-42cd-a16e-bd63075ae3d4">

@gazhayes is this intended?

**Comment by gazhayes** [comment]
Yeah this is intentional, but it's still a problem.
